name: Build & publish docker image
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        repository: denkungsart/ci-ruby
        username: ${{ secrets.CR_USER }}
        password: ${{ secrets.CR_PAT }}
        registry: ghcr.io
        tag_with_ref: true
